package com.ts.codemetrics.entity;
// Generated 3 Jan, 2020 1:55:17 PM by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Cqconfig generated by hbm2java
 */
@Entity
@Table(name = "CQConfig")
public class Cqconfig implements java.io.Serializable {

	private Long id;
	private Account account;
	private Cqprovider cqprovider;
	private String name;
	private String url;
	private String userId;
	private String password;
	private String accessToken;
	private String authType;

	public Cqconfig() {
	}

	public Cqconfig(Account account, Cqprovider cqprovider, String name, String url, String userId, String password,
			String accessToken, String authType) {
		this.account = account;
		this.cqprovider = cqprovider;
		this.name = name;
		this.url = url;
		this.userId = userId;
		this.password = password;
		this.accessToken = accessToken;
		this.authType = authType;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Accountd")
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CQProviderId")
	public Cqprovider getCqprovider() {
		return this.cqprovider;
	}

	public void setCqprovider(Cqprovider cqprovider) {
		this.cqprovider = cqprovider;
	}

	@Column(name = "Name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "URL", length = 500)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "UserId", length = 100)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "Password", length = 1000)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "AccessToken", length = 1000)
	public String getAccessToken() {
		return this.accessToken;
	}

	public void setAccessToken(String accessToken) {
		this.accessToken = accessToken;
	}

	@Column(name = "AuthType", length = 100)
	public String getAuthType() {
		return this.authType;
	}

	public void setAuthType(String authType) {
		this.authType = authType;
	}

}
