package com.ts.codemetrics.entity;
// Generated 4 Feb, 2020 6:45:49 PM by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ProjectCqconfig generated by hbm2java
 */
@Entity
@Table(name = "Project_CQConfig")
public class ProjectCqconfig implements java.io.Serializable {

	private Long id;
	private Long projectId;
	private Integer cqconfigId;
	private Integer rowstatusId;

	public ProjectCqconfig() {
	}

	public ProjectCqconfig(Long projectId, Integer cqconfigId, Integer rowstatusId) {
		this.projectId = projectId;
		this.cqconfigId = cqconfigId;
		this.rowstatusId = rowstatusId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "ProjectId")
	public Long getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Long projectId) {
		this.projectId = projectId;
	}

	@Column(name = "CQConfigId")
	public Integer getCqconfigId() {
		return this.cqconfigId;
	}

	public void setCqconfigId(Integer cqconfigId) {
		this.cqconfigId = cqconfigId;
	}

	@Column(name = "RowstatusId")
	public Integer getRowstatusId() {
		return this.rowstatusId;
	}

	public void setRowstatusId(Integer rowstatusId) {
		this.rowstatusId = rowstatusId;
	}

}
