package com.ts.codemetrics.entity;
// Generated 3 Jan, 2020 1:55:17 PM by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Project generated by hbm2java
 */
@Entity
@Table(name = "Project")
public class Project implements java.io.Serializable {

	private long id;
	private Account account;
	private String name;
	private String code;
	private Integer codeQualityConfigId;
	private Integer scmconfigId;

	public Project() {
	}

	public Project(long id) {
		this.id = id;
	}

	public Project(long id, Account account, String name, String code, Integer codeQualityConfigId,
			Integer scmconfigId) {
		this.id = id;
		this.account = account;
		this.name = name;
		this.code = code;
		this.codeQualityConfigId = codeQualityConfigId;
		this.scmconfigId = scmconfigId;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AccountId")
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@Column(name = "Name", length = 500)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Code", length = 50)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "CodeQualityConfigId")
	public Integer getCodeQualityConfigId() {
		return this.codeQualityConfigId;
	}

	public void setCodeQualityConfigId(Integer codeQualityConfigId) {
		this.codeQualityConfigId = codeQualityConfigId;
	}

	@Column(name = "SCMConfigId")
	public Integer getScmconfigId() {
		return this.scmconfigId;
	}

	public void setScmconfigId(Integer scmconfigId) {
		this.scmconfigId = scmconfigId;
	}

}
