package com.ts.codemetrics.entity;
// Generated 4 Feb, 2020 6:45:49 PM by Hibernate Tools 5.1.10.Final

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProjectMgtToolConfig generated by hbm2java
 */
@Entity
@Table(name = "ProjectMgtToolConfig")
public class ProjectMgtToolConfig implements java.io.Serializable {

	private Long id;
	private String name;
	private String url;
	private String loginId;
	private String password;
	private String accessToken;
	private Long projectId;
	private Integer toolId;
	private String providerCode;
	private Integer rowstatusId;
	private Date createdDate;
	private String createdBy;
	private Date updatedDate;
	private String updatedBy;

	public ProjectMgtToolConfig() {
	}

	public ProjectMgtToolConfig(String name, String url, String loginId, String password, String accessToken,
								Long projectId, Integer toolId, String providerCode, Integer rowstatusId, Date createdDate,
								String createdBy, Date updatedDate, String updatedBy) {
		this.name = name;
		this.url = url;
		this.loginId = loginId;
		this.password = password;
		this.accessToken = accessToken;
		this.projectId = projectId;
		this.toolId = toolId;
		this.providerCode = providerCode;
		this.rowstatusId = rowstatusId;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.updatedDate = updatedDate;
		this.updatedBy = updatedBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "Name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "URL", length = 500)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "LoginId", length = 100)
	public String getLoginId() {
		return this.loginId;
	}

	public void setLoginId(String loginId) {
		this.loginId = loginId;
	}

	@Column(name = "Password", length = 5000)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "AccessToken", length = 5000)
	public String getAccessToken() {
		return this.accessToken;
	}

	public void setAccessToken(String accessToken) {
		this.accessToken = accessToken;
	}

	@Column(name = "ProjectId")
	public Long getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Long projectId) {
		this.projectId = projectId;
	}

	@Column(name = "ToolId")
	public Integer getToolId() {
		return this.toolId;
	}

	public void setToolId(Integer toolId) {
		this.toolId = toolId;
	}

	@Column(name = "RowstatusId")
	public Integer getRowstatusId() {
		return this.rowstatusId;
	}

	public void setRowstatusId(Integer rowstatusId) {
		this.rowstatusId = rowstatusId;
	}

	@CreationTimestamp
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedDate", length = 19, updatable = false)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CreatedBy", length = 500)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "ProviderCode", length = 100)
	public String getProviderCode() {
		return this.providerCode;
	}

	public void setProviderCode(String providerCode) {
		this.providerCode = providerCode;
	}

	@UpdateTimestamp
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UpdatedDate", length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "UpdatedBy", length = 500)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

}
