package com.ts.codemetrics.entity;
// Generated 31 Jan, 2020 1:28:08 PM by Hibernate Tools 5.1.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Project generated by hbm2java
 */
@Entity
@Table(name = "Project")
public class Project implements java.io.Serializable {

	private Long id;
	private Account account;
	private String name;
	private String code;
	private Integer codeQualityConfigId;
	private Integer scmconfigId;
	private String cijobName;
	private Integer rowstatusId;
	private String createdBy;
	private Date createdDate;
	private String updatedBy;
	private Date updatedDate;

	public Project() {
	}

	public Project(Account account, String name, String code, Integer codeQualityConfigId, Integer scmconfigId,
			String cijobName, Integer rowstatusId, String createdBy, Date createdDate, String updatedBy,
			Date updatedDate) {
		this.account = account;
		this.name = name;
		this.code = code;
		this.codeQualityConfigId = codeQualityConfigId;
		this.scmconfigId = scmconfigId;
		this.cijobName = cijobName;
		this.rowstatusId = rowstatusId;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AccountId")
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@Column(name = "Name", length = 500)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Code", length = 50)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "CodeQualityConfigId")
	public Integer getCodeQualityConfigId() {
		return this.codeQualityConfigId;
	}

	public void setCodeQualityConfigId(Integer codeQualityConfigId) {
		this.codeQualityConfigId = codeQualityConfigId;
	}

	@Column(name = "SCMConfigId")
	public Integer getScmconfigId() {
		return this.scmconfigId;
	}

	public void setScmconfigId(Integer scmconfigId) {
		this.scmconfigId = scmconfigId;
	}

	@Column(name = "CIJobName", length = 100)
	public String getCijobName() {
		return this.cijobName;
	}

	public void setCijobName(String cijobName) {
		this.cijobName = cijobName;
	}

	@Column(name = "RowstatusId")
	public Integer getRowstatusId() {
		return this.rowstatusId;
	}

	public void setRowstatusId(Integer rowstatusId) {
		this.rowstatusId = rowstatusId;
	}

	@Column(name = "CreatedBy", length = 100)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedDate", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "UpdatedBy", length = 100)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UpdatedDate", length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
