package com.ts.codemetrics.entity;
// Generated 31 Jan, 2020 1:49:23 PM by Hibernate Tools 5.1.10.Final

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ReleaseItem generated by hbm2java
 */
@Entity
@Table(name = "ReleaseItem")
public class ReleaseItem implements java.io.Serializable {

	private Long id;
	private String itemCode;
	private String title;
	private String description;
	private Integer itemType;
	private Long projectId;
	private Integer severity;
	private Integer priority;
	private String status;
	private String affectedVersion;
	private String fixedVersion;
	private String releaseNumber;
	private Date lastSyncedOn;
	private String jsonResponse;
	private Integer rowStatusId;
	private String createdBy;
	private Date createdDate;
	private String updatedBy;
	@UpdateTimestamp
	private Date updatedDate;

	public ReleaseItem() {
	}

	public ReleaseItem(String itemCode, String title, String description, Integer itemType, Long projectId,
					   Integer severity, Integer priority, String status, String affectedVersion, String fixedVersion,
					   String releaseNumber, Date lastSyncedOn, String jsonResponse, Integer rowStatusId, String createdBy,
					   Date createdDate, String updatedBy, Date updatedDate) {
		this.itemCode = itemCode;
		this.title = title;
		this.description = description;
		this.itemType = itemType;
		this.projectId = projectId;
		this.severity = severity;
		this.priority = priority;
		this.status = status;
		this.affectedVersion = affectedVersion;
		this.fixedVersion = fixedVersion;
		this.releaseNumber = releaseNumber;
		this.lastSyncedOn = lastSyncedOn;
		this.jsonResponse = jsonResponse;
		this.rowStatusId = rowStatusId;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "ItemCode", length = 50)
	public String getItemCode() {
		return this.itemCode;
	}

	public void setItemCode(String itemCode) {
		this.itemCode = itemCode;
	}

	@Column(name = "Title", length = 500)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "Description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "ItemType")
	public Integer getItemType() {
		return this.itemType;
	}

	public void setItemType(Integer itemType) {
		this.itemType = itemType;
	}

	@Column(name = "ProjectId")
	public Long getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Long projectId) {
		this.projectId = projectId;
	}

	@Column(name = "Severity")
	public Integer getSeverity() {
		return this.severity;
	}

	public void setSeverity(Integer severity) {
		this.severity = severity;
	}

	@Column(name = "Priority")
	public Integer getPriority() {
		return this.priority;
	}

	public void setPriority(Integer priority) {
		this.priority = priority;
	}

	@Column(name = "Status", length = 100)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "AffectedVersion", length = 100)
	public String getAffectedVersion() {
		return this.affectedVersion;
	}

	public void setAffectedVersion(String affectedVersion) {
		this.affectedVersion = affectedVersion;
	}

	@Column(name = "FixedVersion", length = 100)
	public String getFixedVersion() {
		return this.fixedVersion;
	}

	public void setFixedVersion(String fixedVersion) {
		this.fixedVersion = fixedVersion;
	}

	@Column(name = "ReleaseNumber", length = 100)
	public String getReleaseNumber() {
		return this.releaseNumber;
	}

	public void setReleaseNumber(String releaseNumber) {
		this.releaseNumber = releaseNumber;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastSyncedOn", length = 19)
	public Date getLastSyncedOn() {
		return this.lastSyncedOn;
	}

	public void setLastSyncedOn(Date lastSyncedOn) {
		this.lastSyncedOn = lastSyncedOn;
	}

	@Column(name = "JsonResponse", length = 65535)
	public String getJsonResponse() {
		return this.jsonResponse;
	}

	public void setJsonResponse(String jsonResponse) {
		this.jsonResponse = jsonResponse;
	}

	@Column(name = "RowStatusId")
	public Integer getRowStatusId() {
		return this.rowStatusId;
	}

	public void setRowStatusId(Integer rowStatusId) {
		this.rowStatusId = rowStatusId;
	}

	@Column(name = "CreatedBy", length = 100)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@CreationTimestamp
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedDate", length = 19,updatable = false)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}


	@Column(name = "UpdatedBy", length = 100)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@UpdateTimestamp
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UpdatedDate", length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
